import { ReactNode } from "react";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Roboto } from "next/font/google";
import { Header } from "@/components/Header";
import { Analytics } from "@vercel/analytics/react";


const roboto = Roboto({ 
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"]
});

export const metadata = {
  title: "Dev.Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`text-gray-200 ${roboto.className} bg-[#121214]`}>
        <Header />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
