import NextAuthSessionProvider from "@/providers/sessionProvider";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ToastContainer } from "react-toastify";

import { Analytics } from "@vercel/analytics/react";


const roboto = Roboto({
    weight: ["400", "500", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dev-Finance",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pt-br">
            <body
                className={`${roboto.className} min-h-screen scrollbar scrollbar-thumb-neutral-900 scrollbar-track-neutral-800`}
            >
                <NextAuthSessionProvider>
                    {children}
                    <Analytics />
                    <ToastContainer autoClose={5000} hideProgressBar={false} theme="dark" />
                    {/* <Footer /> */}
                </NextAuthSessionProvider>
            </body>
        </html>
    );
}
