version: "3.5"

services:
  db:
    container_name: postgres-devfinance
    image: bitnami/postgresql:15.4.0
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=finance
    volumes:
      - postgres_data:/bitnami/postgresql

    networks:
      - postgres-compose-network


  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "9000:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

volumes:
  postgres_data:
    driver: local

networks:
  postgres-compose-network:
    driver: bridge
