version: "3.5"

services:
  db-postgres:
    container_name: postgres-finance
    image: bitnami/postgresql:15.4.0
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=finance
    volumes:
      - postgres_data:/bitnami/postgresql

    networks:
      - postgres-compose-network

  db-cockroachdb:
    container_name: cockroachdb-finance
    image: cockroachdb/cockroach:v23.1.13
    ports:
      - 26257:26257
      - 9001:8080
    environment:
      - COCKROACH_DATABASE=finance
      - COCKROACH_USER=dev
      - COCKROACH_PASSWORD=cockroach
    command: start-single-node 

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "9000:80"
    depends_on:
      - db-postgres
    networks:
      - postgres-compose-network

volumes:
  postgres_data:
    driver: local

networks:
  postgres-compose-network:
    driver: bridge
