-- AlterTable
ALTER TABLE "balances" ALTER COLUMN "income" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "expense" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;
